[tool.poetry]
name = "tungsten-sd-guide"
version = "0.1.0"
description = ""
authors = ["Myeongjang Pyeon <myeongjang.pyeon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
mkdocs-material = "^9.4.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
